#ifndef NETWORK_HH_
# define NETWORK_HH_

# include <SFML/Network.hpp>
enum
{
    NETWORK_NEW_CHARACTER = 42,
    NETWORK_CHARACTER_MOVE,
    NETWORK_ID,
    NETWORK_ELEMENT_KEYBOARD_BOTTOM,
    NETWORK_ELEMENT_KEYBOARD_TOP,
    NETWORK_ELEMENT_KEYBOARD_LEFT,
    NETWORK_ELEMENT_KEYBOARD_RIGHT,
    NETWORK_ELEMENT_KEYBOARD,
    NETWORK_DISCONNECT,
    NETWORK_GLOBAL_ELEMENT,
    NETWORK_KEYBOARD_PRESSED,
    NETWORK_KEYBOARD_RELEASED
};

#endif
